error,count
/ by zero,194
Size expected:&lt;12&gt; but was:&lt;13&gt;,97
Expected exception: org.junit.runners.model.InitializationError,411
" Expected: has single failure containing everythingIsZero(ONE, ONE)      but: was &lt; Time: 0.001 There was 1 failure: 1) everythingIsZero(org.junit.tests.experimental.theories.runner.UnsuccessfulWithDataPointFields$DoesntUseParams) org.junit.experimental.theories.internal.ParameterizedAssertionError: everythingIsZero(ONE: 1, ONE: 1)  at org.junit.experimental.theories.Theories$TheoryAnchor.reportParameterizedError(Theories.java:195)  at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:149)  at org.junit.experimental.theories.Theories$TheoryAnchor.runWithCompleteAssignment(Theories.java:167)  at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:114)  at org.junit.experimental.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:123)  at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:112)  at org.junit.experimental.theories.Theories$TheoryAnchor.runWithIncompleteAssignment(Theories.java:123)  at org.junit.experimental.theories.Theories$TheoryAnchor.runWithAssignment(Theories.java:112)  at org.junit.experimental.theories.Theories$TheoryAnchor.evaluate(Theories.java:97)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)  at org.junit.runner.JUnitCore.run(JUnitCore.java:160)  at org.junit.runner.JUnitCore.run(JUnitCore.java:138)  at org.junit.experimental.results.PrintableResult.testResult(PrintableResult.java:36)  at org.junit.experimental.results.PrintableResult.testResult(PrintableResult.java:29)  at org.junit.tests.experimental.theories.runner.UnsuccessfulWithDataPointFields.reportBadParams(UnsuccessfulWithDataPointFields.java:63)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:49)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)  at org.junit.runners.Suite.runChild(Suite.java:127)  at org.junit.runners.Suite.runChild(Suite.java:26)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)  at org.junit.runners.Suite.runChild(Suite.java:127)  at org.junit.runners.Suite.runChild(Suite.java:26)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)  at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)  at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:121)  at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:98)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.lang.AssertionError:  Expected: is &lt;3&gt;      but: was &lt;2&gt;  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)  at org.junit.Assert.assertThat(Assert.java:865)  at org.junit.Assert.assertThat(Assert.java:832)  at org.junit.tests.experimental.theories.runner.UnsuccessfulWithDataPointFields$DoesntUseParams.everythingIsZero(UnsuccessfulWithDataPointFields.java:57)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:49)  at org.junit.experimental.theories.Theories$TheoryAnchor$2.evaluate(Theories.java:178)  at org.junit.experimental.theories.Theories$TheoryAnchor$1$1.evaluate(Theories.java:144)  ... 71 more  FAILURES!!! Tests run: 1,  Failures: 1  &gt;",2
 Expected: is &quot;ints&quot;      but: was &quot;ints: 1&quot;,2
,1
There should not be any failures because the only test method of the test class is ignored!,1
BeforeClass should not have been executed because the test method is ignored!,1
Unexpected failure : this rule is broken,1
expected:&lt;2&gt; but was:&lt;4&gt;,2
expected:&lt;2&gt; but was:&lt;1&gt;,1
